// Package control_oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package control_oapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ConnectionPurpose.
const (
	ChangeRequest ConnectionPurpose = "change_request"
	HealthCheck   ConnectionPurpose = "health_check"
)

// Defines values for ConnectionStatus.
const (
	ConnectionStatusActive ConnectionStatus = "active"
	ConnectionStatusClosed ConnectionStatus = "closed"
)

// Defines values for PtySessionState.
const (
	PtySessionStateActive  PtySessionState = "active"
	PtySessionStateClosed  PtySessionState = "closed"
	PtySessionStateCreated PtySessionState = "created"
)

// Defines values for RegexFilterFilterType.
const (
	BLACKLIST RegexFilterFilterType = "BLACKLIST"
	WHITELIST RegexFilterFilterType = "WHITELIST"
)

// Defines values for StartRole.
const (
	Implementor StartRole = "implementor"
	Observer    StartRole = "observer"
)

// ChangeRequestSessionsResponse defines model for ChangeRequestSessionsResponse.
type ChangeRequestSessionsResponse struct {
	ChangeEndTime       *time.Time            `json:"change_end_time,omitempty"`
	ChangeId            *string               `json:"change_id,omitempty"`
	ChangeRequestStatus *string               `json:"change_request_status,omitempty"`
	ChangeStartTime     *time.Time            `json:"change_start_time,omitempty"`
	Country             *[]string             `json:"country,omitempty"`
	HostSessionDetails  *[]HostSessionDetails `json:"host_session_details,omitempty"`
	ImplementorGroups   *[]string             `json:"implementor_groups,omitempty"`
	Lob                 *string               `json:"lob,omitempty"`
	Summary             *string               `json:"summary,omitempty"`
}

// Connection defines model for Connection.
type Connection struct {
	Id           *string    `json:"id,omitempty"`
	JoinTime     *time.Time `json:"join_time,omitempty"`
	LeaveTime    *time.Time `json:"leave_time,omitempty"`
	PtySessionId *string    `json:"pty_session_id,omitempty"`

	// StartRole Start role for joining existing PTY sessions
	StartRole *StartRole `json:"start_role,omitempty"`

	// Status Status of the connection
	Status *ConnectionStatus `json:"status,omitempty"`
	UserId *string           `json:"user_id,omitempty"`
}

// ConnectionPurpose Type of connection being established
type ConnectionPurpose string

// ConnectionStatus Status of the connection
type ConnectionStatus string

// Host defines model for Host.
type Host struct {
	AppCode     string `json:"app_code"`
	Environment string `json:"environment"`
	IpAddress   string `json:"ip_address"`
	Name        string `json:"name"`
}

// HostSessionDetails defines model for HostSessionDetails.
type HostSessionDetails struct {
	Host        *Host                `json:"host,omitempty"`
	OsUsers     *[]string            `json:"os_users,omitempty"`
	PtySessions *[]PtySessionSummary `json:"pty_sessions,omitempty"`
}

// JoinRequest defines model for JoinRequest.
type JoinRequest struct {
	// PtySessionId ID of the existing PTY session to join, user will be validated against this session's initial connection details
	PtySessionId string `json:"pty_session_id"`

	// StartRole Start role for joining existing PTY sessions
	StartRole StartRole `json:"start_role"`
}

// PtySession defines model for PtySession.
type PtySession struct {
	// ChangeId ID of the change request associated with this PTY session, if applicable
	ChangeId *string `json:"change_id,omitempty"`

	// Connections List of connections to this PTY session's life time
	Connections  *[]Connection `json:"connections,omitempty"`
	CreatedBy    *string       `json:"created_by,omitempty"`
	EndTime      *time.Time    `json:"end_time,omitempty"`
	Id           *string       `json:"id,omitempty"`
	LastActivity *time.Time    `json:"last_activity,omitempty"`

	// Purpose Type of connection being established
	Purpose   *ConnectionPurpose `json:"purpose,omitempty"`
	StartTime *time.Time         `json:"start_time,omitempty"`

	// State State of the PTY session
	State *PtySessionState `json:"state,omitempty"`
}

// PtySessionState State of the PTY session
type PtySessionState string

// PtySessionSummary defines model for PtySessionSummary.
type PtySessionSummary struct {
	ChangeId *string `json:"change_id,omitempty"`

	// Connections List of connections to this PTY session's life time
	Connections  []Connection `json:"connections"`
	CreatedBy    string       `json:"created_by"`
	EndTime      *time.Time   `json:"end_time,omitempty"`
	Id           string       `json:"id"`
	LastActivity *time.Time   `json:"last_activity,omitempty"`

	// Purpose Type of connection being established
	Purpose   ConnectionPurpose `json:"purpose"`
	StartTime *time.Time        `json:"start_time,omitempty"`

	// State State of the PTY session
	State PtySessionState `json:"state"`
}

// RegexFilter defines model for RegexFilter.
type RegexFilter struct {
	CreatedAt  *time.Time             `json:"created_at,omitempty"`
	CreatedBy  *string                `json:"created_by,omitempty"`
	DeletedAt  *time.Time             `json:"deleted_at,omitempty"`
	DeletedBy  *string                `json:"deleted_by,omitempty"`
	FilterType *RegexFilterFilterType `json:"filter_type,omitempty"`
	Id         *int                   `json:"id,omitempty"`
	IsEnabled  *bool                  `json:"is_enabled,omitempty"`
	OuGroup    *string                `json:"ou_group,omitempty"`
	Pattern    *string                `json:"pattern,omitempty"`
	UpdatedAt  *time.Time             `json:"updated_at,omitempty"`
	UpdatedBy  *string                `json:"updated_by,omitempty"`
}

// RegexFilterFilterType defines model for RegexFilter.FilterType.
type RegexFilterFilterType string

// ServerInfo Info about the target server for the PTY session
type ServerInfo struct {
	// OsUser The Os user to connect as
	OsUser string `json:"os_user"`

	// ServerIp IP address of the target server
	ServerIp string `json:"server_ip"`
}

// StartRequest defines model for StartRequest.
type StartRequest struct {
	// ChangeId Only required if purpose is "change_request", ID of the change request to connect to
	ChangeId *string `json:"change_id,omitempty"`

	// Purpose Type of connection being established
	Purpose ConnectionPurpose `json:"purpose"`

	// Server Info about the target server for the PTY session
	Server ServerInfo `json:"server"`
}

// StartRole Start role for joining existing PTY sessions
type StartRole string

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	// ProxyUrl Load balancer URL for proxy group (e.g., `https://proxy.os.com`, `https://proxy.db.com`)
	ProxyUrl string `json:"proxyUrl"`

	// Token JWT token for proxy
	Token string `json:"token"`
}

// GetApiV1ChangeRequestsParams defines parameters for GetApiV1ChangeRequests.
type GetApiV1ChangeRequestsParams struct {
	TicketIds         *[]string  `form:"ticket_ids,omitempty" json:"ticket_ids,omitempty"`
	ImplementorGroups *[]string  `form:"implementor_groups,omitempty" json:"implementor_groups,omitempty"`
	Lob               *string    `form:"lob,omitempty" json:"lob,omitempty"`
	Country           *string    `form:"country,omitempty" json:"country,omitempty"`
	StartTime         *time.Time `form:"start_time,omitempty" json:"start_time,omitempty"`
	EndTime           *time.Time `form:"end_time,omitempty" json:"end_time,omitempty"`

	// PtySessionState Does not filter out CRs, field not for users
	PtySessionState *PtySessionState `form:"pty_session_state,omitempty" json:"pty_session_state,omitempty"`
	Page            *int             `form:"page,omitempty" json:"page,omitempty"`
	PageSize        *int             `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// PostApiV1WhitelistRegexJSONBody defines parameters for PostApiV1WhitelistRegex.
type PostApiV1WhitelistRegexJSONBody struct {
	// Pattern The regular expression pattern
	Pattern string `json:"pattern"`
}

// PutApiV1WhitelistRegexIdJSONBody defines parameters for PutApiV1WhitelistRegexId.
type PutApiV1WhitelistRegexIdJSONBody struct {
	IsEnabled *bool `json:"isEnabled,omitempty"`

	// Pattern Updated regular expression pattern
	Pattern string `json:"pattern"`
}

// PostApiV1PtyTokenJoinJSONRequestBody defines body for PostApiV1PtyTokenJoin for application/json ContentType.
type PostApiV1PtyTokenJoinJSONRequestBody = JoinRequest

// PostApiV1PtyTokenStartJSONRequestBody defines body for PostApiV1PtyTokenStart for application/json ContentType.
type PostApiV1PtyTokenStartJSONRequestBody = StartRequest

// PostApiV1WhitelistRegexJSONRequestBody defines body for PostApiV1WhitelistRegex for application/json ContentType.
type PostApiV1WhitelistRegexJSONRequestBody PostApiV1WhitelistRegexJSONBody

// PutApiV1WhitelistRegexIdJSONRequestBody defines body for PutApiV1WhitelistRegexId for application/json ContentType.
type PutApiV1WhitelistRegexIdJSONRequestBody PutApiV1WhitelistRegexIdJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetApiV1ChangeRequests request
	GetApiV1ChangeRequests(ctx context.Context, params *GetApiV1ChangeRequestsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1PtyTokenJoinWithBody request with any body
	PostApiV1PtyTokenJoinWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV1PtyTokenJoin(ctx context.Context, body PostApiV1PtyTokenJoinJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1PtyTokenStartWithBody request with any body
	PostApiV1PtyTokenStartWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV1PtyTokenStart(ctx context.Context, body PostApiV1PtyTokenStartJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1WhitelistRegex request
	GetApiV1WhitelistRegex(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1WhitelistRegexWithBody request with any body
	PostApiV1WhitelistRegexWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV1WhitelistRegex(ctx context.Context, body PostApiV1WhitelistRegexJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteApiV1WhitelistRegexId request
	DeleteApiV1WhitelistRegexId(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutApiV1WhitelistRegexIdWithBody request with any body
	PutApiV1WhitelistRegexIdWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutApiV1WhitelistRegexId(ctx context.Context, id int, body PutApiV1WhitelistRegexIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetApiV1ChangeRequests(ctx context.Context, params *GetApiV1ChangeRequestsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1ChangeRequestsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1PtyTokenJoinWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1PtyTokenJoinRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1PtyTokenJoin(ctx context.Context, body PostApiV1PtyTokenJoinJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1PtyTokenJoinRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1PtyTokenStartWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1PtyTokenStartRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1PtyTokenStart(ctx context.Context, body PostApiV1PtyTokenStartJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1PtyTokenStartRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV1WhitelistRegex(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1WhitelistRegexRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1WhitelistRegexWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1WhitelistRegexRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1WhitelistRegex(ctx context.Context, body PostApiV1WhitelistRegexJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1WhitelistRegexRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteApiV1WhitelistRegexId(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteApiV1WhitelistRegexIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutApiV1WhitelistRegexIdWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutApiV1WhitelistRegexIdRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutApiV1WhitelistRegexId(ctx context.Context, id int, body PutApiV1WhitelistRegexIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutApiV1WhitelistRegexIdRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetApiV1ChangeRequestsRequest generates requests for GetApiV1ChangeRequests
func NewGetApiV1ChangeRequestsRequest(server string, params *GetApiV1ChangeRequestsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/change_requests/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.TicketIds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "ticket_ids", runtime.ParamLocationQuery, *params.TicketIds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ImplementorGroups != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "implementor_groups", runtime.ParamLocationQuery, *params.ImplementorGroups); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Lob != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "lob", runtime.ParamLocationQuery, *params.Lob); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Country != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "country", runtime.ParamLocationQuery, *params.Country); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.StartTime != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "start_time", runtime.ParamLocationQuery, *params.StartTime); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.EndTime != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "end_time", runtime.ParamLocationQuery, *params.EndTime); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PtySessionState != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "pty_session_state", runtime.ParamLocationQuery, *params.PtySessionState); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page_size", runtime.ParamLocationQuery, *params.PageSize); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiV1PtyTokenJoinRequest calls the generic PostApiV1PtyTokenJoin builder with application/json body
func NewPostApiV1PtyTokenJoinRequest(server string, body PostApiV1PtyTokenJoinJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1PtyTokenJoinRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiV1PtyTokenJoinRequestWithBody generates requests for PostApiV1PtyTokenJoin with any type of body
func NewPostApiV1PtyTokenJoinRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/pty_token/join")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostApiV1PtyTokenStartRequest calls the generic PostApiV1PtyTokenStart builder with application/json body
func NewPostApiV1PtyTokenStartRequest(server string, body PostApiV1PtyTokenStartJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1PtyTokenStartRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiV1PtyTokenStartRequestWithBody generates requests for PostApiV1PtyTokenStart with any type of body
func NewPostApiV1PtyTokenStartRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/pty_token/start")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiV1WhitelistRegexRequest generates requests for GetApiV1WhitelistRegex
func NewGetApiV1WhitelistRegexRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/whitelist/regex")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiV1WhitelistRegexRequest calls the generic PostApiV1WhitelistRegex builder with application/json body
func NewPostApiV1WhitelistRegexRequest(server string, body PostApiV1WhitelistRegexJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1WhitelistRegexRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiV1WhitelistRegexRequestWithBody generates requests for PostApiV1WhitelistRegex with any type of body
func NewPostApiV1WhitelistRegexRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/whitelist/regex")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteApiV1WhitelistRegexIdRequest generates requests for DeleteApiV1WhitelistRegexId
func NewDeleteApiV1WhitelistRegexIdRequest(server string, id int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/whitelist/regex/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutApiV1WhitelistRegexIdRequest calls the generic PutApiV1WhitelistRegexId builder with application/json body
func NewPutApiV1WhitelistRegexIdRequest(server string, id int, body PutApiV1WhitelistRegexIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutApiV1WhitelistRegexIdRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPutApiV1WhitelistRegexIdRequestWithBody generates requests for PutApiV1WhitelistRegexId with any type of body
func NewPutApiV1WhitelistRegexIdRequestWithBody(server string, id int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/whitelist/regex/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetApiV1ChangeRequestsWithResponse request
	GetApiV1ChangeRequestsWithResponse(ctx context.Context, params *GetApiV1ChangeRequestsParams, reqEditors ...RequestEditorFn) (*GetApiV1ChangeRequestsResponse, error)

	// PostApiV1PtyTokenJoinWithBodyWithResponse request with any body
	PostApiV1PtyTokenJoinWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1PtyTokenJoinResponse, error)

	PostApiV1PtyTokenJoinWithResponse(ctx context.Context, body PostApiV1PtyTokenJoinJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1PtyTokenJoinResponse, error)

	// PostApiV1PtyTokenStartWithBodyWithResponse request with any body
	PostApiV1PtyTokenStartWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1PtyTokenStartResponse, error)

	PostApiV1PtyTokenStartWithResponse(ctx context.Context, body PostApiV1PtyTokenStartJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1PtyTokenStartResponse, error)

	// GetApiV1WhitelistRegexWithResponse request
	GetApiV1WhitelistRegexWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV1WhitelistRegexResponse, error)

	// PostApiV1WhitelistRegexWithBodyWithResponse request with any body
	PostApiV1WhitelistRegexWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1WhitelistRegexResponse, error)

	PostApiV1WhitelistRegexWithResponse(ctx context.Context, body PostApiV1WhitelistRegexJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1WhitelistRegexResponse, error)

	// DeleteApiV1WhitelistRegexIdWithResponse request
	DeleteApiV1WhitelistRegexIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*DeleteApiV1WhitelistRegexIdResponse, error)

	// PutApiV1WhitelistRegexIdWithBodyWithResponse request with any body
	PutApiV1WhitelistRegexIdWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutApiV1WhitelistRegexIdResponse, error)

	PutApiV1WhitelistRegexIdWithResponse(ctx context.Context, id int, body PutApiV1WhitelistRegexIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutApiV1WhitelistRegexIdResponse, error)
}

type GetApiV1ChangeRequestsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]ChangeRequestSessionsResponse
}

// Status returns HTTPResponse.Status
func (r GetApiV1ChangeRequestsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1ChangeRequestsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiV1PtyTokenJoinResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TokenResponse
}

// Status returns HTTPResponse.Status
func (r PostApiV1PtyTokenJoinResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1PtyTokenJoinResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiV1PtyTokenStartResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TokenResponse
}

// Status returns HTTPResponse.Status
func (r PostApiV1PtyTokenStartResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1PtyTokenStartResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV1WhitelistRegexResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]RegexFilter
}

// Status returns HTTPResponse.Status
func (r GetApiV1WhitelistRegexResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1WhitelistRegexResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiV1WhitelistRegexResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *RegexFilter
}

// Status returns HTTPResponse.Status
func (r PostApiV1WhitelistRegexResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1WhitelistRegexResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteApiV1WhitelistRegexIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteApiV1WhitelistRegexIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteApiV1WhitelistRegexIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutApiV1WhitelistRegexIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RegexFilter
}

// Status returns HTTPResponse.Status
func (r PutApiV1WhitelistRegexIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutApiV1WhitelistRegexIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetApiV1ChangeRequestsWithResponse request returning *GetApiV1ChangeRequestsResponse
func (c *ClientWithResponses) GetApiV1ChangeRequestsWithResponse(ctx context.Context, params *GetApiV1ChangeRequestsParams, reqEditors ...RequestEditorFn) (*GetApiV1ChangeRequestsResponse, error) {
	rsp, err := c.GetApiV1ChangeRequests(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1ChangeRequestsResponse(rsp)
}

// PostApiV1PtyTokenJoinWithBodyWithResponse request with arbitrary body returning *PostApiV1PtyTokenJoinResponse
func (c *ClientWithResponses) PostApiV1PtyTokenJoinWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1PtyTokenJoinResponse, error) {
	rsp, err := c.PostApiV1PtyTokenJoinWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1PtyTokenJoinResponse(rsp)
}

func (c *ClientWithResponses) PostApiV1PtyTokenJoinWithResponse(ctx context.Context, body PostApiV1PtyTokenJoinJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1PtyTokenJoinResponse, error) {
	rsp, err := c.PostApiV1PtyTokenJoin(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1PtyTokenJoinResponse(rsp)
}

// PostApiV1PtyTokenStartWithBodyWithResponse request with arbitrary body returning *PostApiV1PtyTokenStartResponse
func (c *ClientWithResponses) PostApiV1PtyTokenStartWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1PtyTokenStartResponse, error) {
	rsp, err := c.PostApiV1PtyTokenStartWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1PtyTokenStartResponse(rsp)
}

func (c *ClientWithResponses) PostApiV1PtyTokenStartWithResponse(ctx context.Context, body PostApiV1PtyTokenStartJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1PtyTokenStartResponse, error) {
	rsp, err := c.PostApiV1PtyTokenStart(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1PtyTokenStartResponse(rsp)
}

// GetApiV1WhitelistRegexWithResponse request returning *GetApiV1WhitelistRegexResponse
func (c *ClientWithResponses) GetApiV1WhitelistRegexWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV1WhitelistRegexResponse, error) {
	rsp, err := c.GetApiV1WhitelistRegex(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1WhitelistRegexResponse(rsp)
}

// PostApiV1WhitelistRegexWithBodyWithResponse request with arbitrary body returning *PostApiV1WhitelistRegexResponse
func (c *ClientWithResponses) PostApiV1WhitelistRegexWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1WhitelistRegexResponse, error) {
	rsp, err := c.PostApiV1WhitelistRegexWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1WhitelistRegexResponse(rsp)
}

func (c *ClientWithResponses) PostApiV1WhitelistRegexWithResponse(ctx context.Context, body PostApiV1WhitelistRegexJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1WhitelistRegexResponse, error) {
	rsp, err := c.PostApiV1WhitelistRegex(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1WhitelistRegexResponse(rsp)
}

// DeleteApiV1WhitelistRegexIdWithResponse request returning *DeleteApiV1WhitelistRegexIdResponse
func (c *ClientWithResponses) DeleteApiV1WhitelistRegexIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*DeleteApiV1WhitelistRegexIdResponse, error) {
	rsp, err := c.DeleteApiV1WhitelistRegexId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteApiV1WhitelistRegexIdResponse(rsp)
}

// PutApiV1WhitelistRegexIdWithBodyWithResponse request with arbitrary body returning *PutApiV1WhitelistRegexIdResponse
func (c *ClientWithResponses) PutApiV1WhitelistRegexIdWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutApiV1WhitelistRegexIdResponse, error) {
	rsp, err := c.PutApiV1WhitelistRegexIdWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutApiV1WhitelistRegexIdResponse(rsp)
}

func (c *ClientWithResponses) PutApiV1WhitelistRegexIdWithResponse(ctx context.Context, id int, body PutApiV1WhitelistRegexIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutApiV1WhitelistRegexIdResponse, error) {
	rsp, err := c.PutApiV1WhitelistRegexId(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutApiV1WhitelistRegexIdResponse(rsp)
}

// ParseGetApiV1ChangeRequestsResponse parses an HTTP response from a GetApiV1ChangeRequestsWithResponse call
func ParseGetApiV1ChangeRequestsResponse(rsp *http.Response) (*GetApiV1ChangeRequestsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1ChangeRequestsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []ChangeRequestSessionsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostApiV1PtyTokenJoinResponse parses an HTTP response from a PostApiV1PtyTokenJoinWithResponse call
func ParsePostApiV1PtyTokenJoinResponse(rsp *http.Response) (*PostApiV1PtyTokenJoinResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1PtyTokenJoinResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TokenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostApiV1PtyTokenStartResponse parses an HTTP response from a PostApiV1PtyTokenStartWithResponse call
func ParsePostApiV1PtyTokenStartResponse(rsp *http.Response) (*PostApiV1PtyTokenStartResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1PtyTokenStartResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TokenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiV1WhitelistRegexResponse parses an HTTP response from a GetApiV1WhitelistRegexWithResponse call
func ParseGetApiV1WhitelistRegexResponse(rsp *http.Response) (*GetApiV1WhitelistRegexResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1WhitelistRegexResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []RegexFilter
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostApiV1WhitelistRegexResponse parses an HTTP response from a PostApiV1WhitelistRegexWithResponse call
func ParsePostApiV1WhitelistRegexResponse(rsp *http.Response) (*PostApiV1WhitelistRegexResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1WhitelistRegexResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest RegexFilter
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseDeleteApiV1WhitelistRegexIdResponse parses an HTTP response from a DeleteApiV1WhitelistRegexIdWithResponse call
func ParseDeleteApiV1WhitelistRegexIdResponse(rsp *http.Response) (*DeleteApiV1WhitelistRegexIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteApiV1WhitelistRegexIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePutApiV1WhitelistRegexIdResponse parses an HTTP response from a PutApiV1WhitelistRegexIdWithResponse call
func ParsePutApiV1WhitelistRegexIdResponse(rsp *http.Response) (*PutApiV1WhitelistRegexIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutApiV1WhitelistRegexIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RegexFilter
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get change request and associated PTY sessions
	// (GET /api/v1/change_requests/)
	GetApiV1ChangeRequests(c *gin.Context, params GetApiV1ChangeRequestsParams)
	// Mint a join token for an existing PTY session
	// (POST /api/v1/pty_token/join)
	PostApiV1PtyTokenJoin(c *gin.Context)
	// Mint a start token for a new PTY session
	// (POST /api/v1/pty_token/start)
	PostApiV1PtyTokenStart(c *gin.Context)
	// Get all whitelist regex filters for healthcheck ou group
	// (GET /api/v1/whitelist/regex)
	GetApiV1WhitelistRegex(c *gin.Context)
	// Add a regex to whitelist for healthcheck ou group
	// (POST /api/v1/whitelist/regex)
	PostApiV1WhitelistRegex(c *gin.Context)
	// Soft delete a whitelist regex filter
	// (DELETE /api/v1/whitelist/regex/{id})
	DeleteApiV1WhitelistRegexId(c *gin.Context, id int)
	// Update a whitelist regex filter
	// (PUT /api/v1/whitelist/regex/{id})
	PutApiV1WhitelistRegexId(c *gin.Context, id int)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetApiV1ChangeRequests operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1ChangeRequests(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1ChangeRequestsParams

	// ------------- Optional query parameter "ticket_ids" -------------

	err = runtime.BindQueryParameter("form", true, false, "ticket_ids", c.Request.URL.Query(), &params.TicketIds)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ticket_ids: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "implementor_groups" -------------

	err = runtime.BindQueryParameter("form", true, false, "implementor_groups", c.Request.URL.Query(), &params.ImplementorGroups)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter implementor_groups: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "lob" -------------

	err = runtime.BindQueryParameter("form", true, false, "lob", c.Request.URL.Query(), &params.Lob)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter lob: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "country" -------------

	err = runtime.BindQueryParameter("form", true, false, "country", c.Request.URL.Query(), &params.Country)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter country: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "start_time" -------------

	err = runtime.BindQueryParameter("form", true, false, "start_time", c.Request.URL.Query(), &params.StartTime)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter start_time: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "end_time" -------------

	err = runtime.BindQueryParameter("form", true, false, "end_time", c.Request.URL.Query(), &params.EndTime)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter end_time: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pty_session_state" -------------

	err = runtime.BindQueryParameter("form", true, false, "pty_session_state", c.Request.URL.Query(), &params.PtySessionState)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pty_session_state: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page_size: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1ChangeRequests(c, params)
}

// PostApiV1PtyTokenJoin operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1PtyTokenJoin(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1PtyTokenJoin(c)
}

// PostApiV1PtyTokenStart operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1PtyTokenStart(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1PtyTokenStart(c)
}

// GetApiV1WhitelistRegex operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1WhitelistRegex(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1WhitelistRegex(c)
}

// PostApiV1WhitelistRegex operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1WhitelistRegex(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1WhitelistRegex(c)
}

// DeleteApiV1WhitelistRegexId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiV1WhitelistRegexId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteApiV1WhitelistRegexId(c, id)
}

// PutApiV1WhitelistRegexId operation middleware
func (siw *ServerInterfaceWrapper) PutApiV1WhitelistRegexId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutApiV1WhitelistRegexId(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/change_requests/", wrapper.GetApiV1ChangeRequests)
	router.POST(options.BaseURL+"/api/v1/pty_token/join", wrapper.PostApiV1PtyTokenJoin)
	router.POST(options.BaseURL+"/api/v1/pty_token/start", wrapper.PostApiV1PtyTokenStart)
	router.GET(options.BaseURL+"/api/v1/whitelist/regex", wrapper.GetApiV1WhitelistRegex)
	router.POST(options.BaseURL+"/api/v1/whitelist/regex", wrapper.PostApiV1WhitelistRegex)
	router.DELETE(options.BaseURL+"/api/v1/whitelist/regex/:id", wrapper.DeleteApiV1WhitelistRegexId)
	router.PUT(options.BaseURL+"/api/v1/whitelist/regex/:id", wrapper.PutApiV1WhitelistRegexId)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabXPiOBL+KyrdVe1tlQEDeeVbJpnJwEwmLCQzu5dNsbLdgCZG8koyCTPFf7+SbGMb",
	"CwLZ7Nx9uJoPk8h6aXU/3f10K9+xz2cRZ8CUxJ3vWPpTmBHz4/mUsAkM4M8YpBqClJQzOQAZcSZBT4gE",
	"j0AoCma6b6aPgAUjRWdmwpiLGVG4gwOioGZGHawWEeAOlkpQNsFLJ1tIA71k01eRiDGSiqhYbpspFRFq",
	"XxF4zJRY6AVUwcy+fzpAhCAL/fuUa3kSvYwCUISGsrTDPwWMcQf/o5GruJHqt/Ger3R6kS61HEFnUQgz",
	"YIqL0UTwOJL7iRhyzzpPxrMZSe679i3fhHtfwVd69jlnDHxFOatafYPVvnLK9rRBCGQOe66J1GJlgQ2S",
	"JHAQPITnTDLUMwd6YrIsxdm2Jblmhsn8pYNjCcIuzHbd9mMR8cSxApC+oFGicXyziADxMfJXU5EHlE0Q",
	"SEW8kMopBNjBwOIZ7tytOQx28BRIqKYjfwr+A763aLFyi4oIybgWQk2hIEjhWOIrOtdG8kMuIbAepEFf",
	"hRCJopHPA7CaD9icCs60D1i/02hEgkCAtDsEIzOwW0LrhwoItOxmVmmv8sFOLuO9xYYWX65ccppe/bmY",
	"oPfjcqRBtKevF3xh9zDUV4tU8mEaEio721Db45SliUGfAE9EBypz6zWPxP2b31pu67DZajcPcNkdi+HN",
	"3KCksapvlzHZvcjwCE9UKu0Q/ZvfULoEKY50EHKQViV6pGGIPEBzElIdUQJEJoQyqZCaUpkt+kkiyqii",
	"JCw6WxbanVcKLmvgW7tnaVMb2nKTbczB29WVTEJpgEBESu5To5NHqqaJQgqadBAdIxJFIfWJF25In5my",
	"LLHjI5WqHL6kNs76MT9JFNIxoDTU74TeQmKyOIQvQN9q5C02RJZ9icqGDBMSqUYm/FG12CN35fF+tztm",
	"CWKFu/2k1xkN9ogHZrrV+9cnWdMFZHAr2LiYpRLj6NC6Q+KohimdN8Lweow7d7veCC+drf7yCgh5IRT2",
	"N+daDDFxo4D3zNo5yspOWo0r90sHD2ACT+9oqEBYQku6O1F70OrtHhhACPtuma3ZsOXYSD9Kxr+v0Pbl",
	"fffm7cfu8AY7+M3Hs/MP5uf753ycMgUTMLmJyhEwHf+K3z3OQyAm+PA4IehWqSKiFAhm/RZHwd56zdZ4",
	"uzL4IYg5iC4bc0tiYGOOiMdjZdxVETEBhaRZgcZcWJy4jIyUrliI6xTQtUwSsOJZAkDEnkrNgSMaWSTs",
	"o5SXZTGlJOSz3pEJWDzEllmTHG2lNYVAgc8HRUKzCuNV4p2KV1QRBr9VqwjTwU23rv81jew75/RrFi5Q",
	"dlOdplNhEJXo9zV5fscO2sgBCtZR/NWT1UoNWwlSDtEKQ1rFsHSrzcZLmVglHQmFNKEyeNa00JRPFtoo",
	"CymqyE4dzL3K4bl6bvgDsGJrpMiIBX9a3IoQd/BUqUh2Gg0zVOey7vOZ1rZerbGx6E29S59e01739lu3",
	"+Yl2ZZcNDv3z7lH3Ifr183nvtA6L3rfgS5de0+7T1dcr99PNb+3ri4fHLn2k3uyd+vfQTJ6Ty4PJ4PI0",
	"1OPkyzu3+5U/fbp527r6enV4ddFdjH+pD8fhh6fHQW94BR8+vGv9cnMwfoyuoDduH/WvH44Wvc8jEvwi",
	"5eOhb6Hnq2tVCB8nAfJISJgPAt0OPhqtm/nIxEj0L6hP6g76w6aPPyrjgWfGf7bhMlXdugi9LzfIfMqP",
	"fjZKJFs5+cWqKDNg9mNB1WKoYZto4g0QAeIsVlP9m2d+e5fF8d4XnXMMyE3GMF9zWfRN8VJvTK3B+azf",
	"NVcwDEFjlbBgBeAibuvoPBYCmAoXiISSI11wmgVhiBhntUT/AkLD9IEFEadMybqWhSpTjp1zpgQP0Vm/",
	"ix08B5EUGbipY5NJchEwElHcwe26W29jk9mmRgkNEtHGvNkoBx3Z0N8moKo3G4CKBZNGvrN+f3D9+e0F",
	"SlqOKI3B0lKbgEknulDLvTNFlVZNYUFRO+ZbsQDpVlZTiQQoQWEOARoLPisdFmgQzWkAAfIW5guJ1RSY",
	"oj5RSbn5AEwrU/uIGerqXHEJ6iyin5ulXqo0ihNkBspU+XffMdUq+TMGoXGaNC2wov4DqBENZIYgsk9H",
	"QLNd27aWnuJrbh9yr7Rfxensy7IO7AuWFthzcfVuNNq+5Yr5v2TDMs4vOEjEuEIJNUWaZ50PpIPGFMIg",
	"+cIFSho+jlWaYocg4/W5WHuWc/YLR2RS3jWAMYlDhTtNB88oozOdE5tOhRlv23Ak6bcNu7ZcB8/IU7qt",
	"6z5zyL0O1Ul2Ndhsua6hRpyptDGYNii00htfZdIbqfK3vKLDmsPV3ONay0Wtdsd1O66LHQvPc49bTddt",
	"4o0vEfhsVcBWHyA2HZO9N9zh4SV28PsPOtvYHxTu8uZh3inFvdur/lqXsqNTV1DuY6bMsllvurltSBTV",
	"EjJTa5b7jXdFfkrZ3FSK5cbi3fftSiq2gu6S9wH8ALRx2j44gSM/qLW8ZlA7OPVatVMCxzW3TY5I6/jU",
	"849PcenhINddE7VanYPDjntSb7cOcfmtYH3aUefgpN4+MdlpvRnZPGwdtX3vqNY6OGnXDtpHp7VTz/dq",
	"J6fjowPPbcPh2G0eH7ab7mnTPdnWrsxfCPIGxqrzry+MNWiLBbAZLDYVcsFbyHX1/ZqtevtEa/Flwq51",
	"H7bsv61osaK3aIFMMQryyy/v9XVtz1V3+GI4HGLH/Fe7eKMRZZ6l8PlbPbx6isK30USQwPSNPOI/AAuQ",
	"XEiTjpbWDLW1Etn6eFnNZqa1UGlbrpVJqU8aNqGmQMUmvqEPOHAPqqznkwn3MQv0jMMkiq2X4woEI2FW",
	"gYMQXJSop/GrIum8M8rPFXkJFcm3cCOdxMjEWOqKPEDKwfC9PjJjddqRDMNpaP809D8NSWW60+cy4Tt9",
	"tTA1UU9PT3g2SPWGB4sd4vZuua34BrEsk3klYli+KGXsdnS53LOAR9uFC/qtwA2NCRISHlYKpHL9rcHz",
	"6682aJjni8yoBkK2ecMXI+eKMoWIKTAK9RNh1lq5ABw9apSyCTYmquyBG1Oy/03AKbV5/o+cV0WOsXMR",
	"OojB436geZxSBSGVqiFgAk+FAtJeWn3J5pv2Nf6LxtspuRQb5bumEj5Gq5shc7O0IpB/dyrQFfaGo42N",
	"kr8PMH8egHiclMMFM630ixroTUj8B/0zvl86z/myxTAvc+a1xlPeTK+2mwVM4pAIBE+RSB+Cs/nP9X+y",
	"eZa2zw4hovlqIaIEriqYki8oZZZIxr4PUo7jMFwkrMPd7P6URbHKum8zEuqKFoIEEj//nTA8CwJEUugp",
	"XkDjX8Df5pDR+E6DZXKPEJL3yTJEL8y4BaTdYENrJiJqWmihBHgdEZa+xbby1UINU8OmD1wWw25ew34E",
	"qxzysUqlQ2RDQNktbMS2qBGrH2yP14hFVL7d9ii4MVTdJg94/71w5f7gcJW+WL4gXP1PYD+x11+B/XL1",
	"EJageP3JxCchdnC8eibqNBqhHpxyqTqHh657bBoK6THr63WaN6RL7vZakLtOTsKqrctB2g9fb8s7afGr",
	"ZZNb2+5ZZ9PWr89lKJadW6Qo5olUlc8efn2LLsuHvc93sRx2RRiZQG7m5AQvM2SyaWELywF2BGy5V/YX",
	"ayGfJPtve7nIzzmLA2rb9yyYUUal0sF1DvlLj9l6pu+3joYtZ+i98PJ++Z8AAAD//1OGwjEnLgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
