openapi: 3.0.3
info:
  title: LLM External API
  version: 1.0.0
  description: |-
    API for AI team to pull PTY session details
servers:
  - url: https://x01smxtra1a.sp.uat.dbs.corp:55007
    description: UAT
  - url: http://localhost:55008
    description: Local

tags:
  - name: PTY Session
    description: Get PTY session details

security:
  - ApiKeyAuth: []

paths:
  /api/v1/pty_sessions:
    get:
      tags:
        - PTY Session
      summary: Get all PTY sessions for a change request
      security:
        - ApiKeyAuth: [ ]
      parameters:
        - name: change_request_id
          in: query
          required: true
          schema:
            type: string
          description: ID of the change request
      responses:
        '200':
          description: PTY sessions retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetPtySessionResponse'
        '404':
          description: Not found
        '500':
          description: Internal server error

######################################################################## Components
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    PtySessionState:
      type: string
      description: State of the PTY session
      enum: [created, active, closed]

    GetPtySessionResponse:
      type: object
      properties:
        pty_session_id:
          type: string
        session_created_by:
          type: string
        session_connected_server_ip:
          type: string
        ticket_id:
          type: string
          description: ID of the change request associated with this PTY session