/**
 * Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PtySessionState } from './ptySessionState';


export interface GetPtySessionResponse { 
    /**
     * Unique identifier for the PTY session
     */
    id?: string;
    /**
     * Ticket ID associated with the PTY session
     */
    ticket_id?: string;
    /**
     * Hostname of the target server
     */
    target_server_hostname?: string;
    /**
     * IP address of the target server
     */
    target_server_ip?: string;
    /**
     * List of implementors\' user IDs
     */
    implementors?: Array<string>;
    /**
     * List of observers\' user IDs
     */
    observers?: Array<string>;
    /**
     * Start time of the PTY session in RFC3339 format
     */
    start_time?: string;
    /**
     * End time of the PTY session in RFC3339 format
     */
    end_time?: string;
    state?: PtySessionState;
}
export namespace GetPtySessionResponse {
}


