/**
 * Control API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { HealthcheckSessionsResponse } from '../model/healthcheckSessionsResponse';
// @ts-ignore
import { PtySessionState } from '../model/ptySessionState';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class HealthcheckService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Get healthcheck servers for user\&#39;s OU group and associated PTY sessions
     * Returns healthcheck servers associated with the user\&#39;s OU group and their associated PTY sessions and connections OU group is retrieved from the user\&#39;s id provided by the authentication token.
     * @param hostname 
     * @param ip 
     * @param appcode 
     * @param lob 
     * @param osType 
     * @param status 
     * @param environment 
     * @param country 
     * @param systemType 
     * @param ptySessionState Does not filter out hosts, field not meant for users
     * @param page 
     * @param pageSize 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1HealthcheckGet(hostname?: string, ip?: string, appcode?: string, lob?: string, osType?: string, status?: string, environment?: string, country?: string, systemType?: string, ptySessionState?: PtySessionState, page?: number, pageSize?: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<HealthcheckSessionsResponse>>;
    public apiV1HealthcheckGet(hostname?: string, ip?: string, appcode?: string, lob?: string, osType?: string, status?: string, environment?: string, country?: string, systemType?: string, ptySessionState?: PtySessionState, page?: number, pageSize?: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<HealthcheckSessionsResponse>>>;
    public apiV1HealthcheckGet(hostname?: string, ip?: string, appcode?: string, lob?: string, osType?: string, status?: string, environment?: string, country?: string, systemType?: string, ptySessionState?: PtySessionState, page?: number, pageSize?: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<HealthcheckSessionsResponse>>>;
    public apiV1HealthcheckGet(hostname?: string, ip?: string, appcode?: string, lob?: string, osType?: string, status?: string, environment?: string, country?: string, systemType?: string, ptySessionState?: PtySessionState, page?: number, pageSize?: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>hostname, 'hostname');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>ip, 'ip');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>appcode, 'appcode');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>lob, 'lob');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>osType, 'os_type');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>status, 'status');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>environment, 'environment');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>country, 'country');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>systemType, 'system_type');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>ptySessionState, 'pty_session_state');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'page_size');

        let localVarHeaders = this.defaultHeaders;

        // authentication (BearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('BearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/healthcheck/`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<HealthcheckSessionsResponse>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
