/**
 * Control API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HostSessionDetailsV2 } from './hostSessionDetailsV2';


export interface ChangeRequestSessionsResponse { 
    change_id?: string;
    country?: Array<string>;
    lob?: string;
    implementor_groups?: Array<string>;
    change_start_time?: string;
    change_end_time?: string;
    change_request_status?: string;
    summary?: string;
    host_session_details?: Array<HostSessionDetailsV2>;
}

