/**
 * Control API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IExpress } from './iExpress';


export interface GetIExpressResponse { 
    /**
     * total number of iexpress requests matching the filter
     */
    total_count?: number;
    page?: number;
    page_size?: number;
    items?: Array<IExpress>;
}

