/**
 * Control API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HostSessionDetailsV2 } from './hostSessionDetailsV2';


export interface GetIExpressHostsAndSessionDetailsResponse { 
    host_session_details?: Array<HostSessionDetailsV2>;
}

