/**
 * Control API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HostSessionDetails } from './hostSessionDetails';


export interface HealthcheckSessionsResponse { 
    host_session_details?: Array<HostSessionDetails>;
}

