/**
 * Control API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PtySessionSummary } from './ptySessionSummary';
import { Host } from './host';


export interface HostSessionDetailsV2 { 
    host?: Host;
    cyberark_objects?: Array<string>;
    os_users?: Array<string>;
    pty_sessions?: Array<PtySessionSummary>;
}

