/**
 * Control API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IExpress { 
    request_id: string;
    requestor: string;
    lob: string;
    origin_country: string;
    app_impacted: Array<string>;
    action?: string;
    related_ticket?: string;
    start_time: string;
    end_time: string;
    state: string;
    approver_group1?: string;
    approver_group2?: string;
    md_approver_group?: string;
}

