/**
 * Control API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Load balancer information for the proxy group
 */
export interface ProxyLoadBalancer { 
    /**
     * Unique identifier for the load balancer
     */
    id: string;
    /**
     * URL of the load balancer (e.g., `https://proxy.os.com`)
     */
    url: string;
}

