/**
 * Control API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Start role for joining existing PTY sessions
 */
export const StartRole = {
    Implementor: 'implementor',
    Observer: 'observer'
} as const;
export type StartRole = typeof StartRole[keyof typeof StartRole];

