/**
 * Control API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserMetadata { 
    /**
     * Unique identifier for the user
     */
    user_id: string;
    implementor_groups: Array<string>;
    ou_group: string;
    /**
     * Currently unused, placeholder
     */
    roles: Array<string>;
}

