/**
 * Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { GetPtySessionResponse } from '../model/getPtySessionResponse';
// @ts-ignore
import { PtySessionState } from '../model/ptySessionState';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class PTYSessionService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Get all PTY sessions matching the filter
     * @param ticketIds 
     * @param targetServerHostname 
     * @param targetServerIp 
     * @param implementors userid of implementors
     * @param observers userid of observers
     * @param startTime Expected format - RFC3339
     * @param endTime Expected format - RFC3339
     * @param ptySessionState 
     * @param page 
     * @param pageSize 
     * @param totalCount 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1AdminPtySessionsGet(ticketIds?: Array<string>, targetServerHostname?: string, targetServerIp?: string, implementors?: Array<string>, observers?: Array<string>, startTime?: string, endTime?: string, ptySessionState?: PtySessionState, page?: number, pageSize?: number, totalCount?: boolean, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<GetPtySessionResponse>>;
    public apiV1AdminPtySessionsGet(ticketIds?: Array<string>, targetServerHostname?: string, targetServerIp?: string, implementors?: Array<string>, observers?: Array<string>, startTime?: string, endTime?: string, ptySessionState?: PtySessionState, page?: number, pageSize?: number, totalCount?: boolean, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<GetPtySessionResponse>>>;
    public apiV1AdminPtySessionsGet(ticketIds?: Array<string>, targetServerHostname?: string, targetServerIp?: string, implementors?: Array<string>, observers?: Array<string>, startTime?: string, endTime?: string, ptySessionState?: PtySessionState, page?: number, pageSize?: number, totalCount?: boolean, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<GetPtySessionResponse>>>;
    public apiV1AdminPtySessionsGet(ticketIds?: Array<string>, targetServerHostname?: string, targetServerIp?: string, implementors?: Array<string>, observers?: Array<string>, startTime?: string, endTime?: string, ptySessionState?: PtySessionState, page?: number, pageSize?: number, totalCount?: boolean, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (ticketIds) {
            ticketIds.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'ticket_ids');
            })
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>targetServerHostname, 'target_server_hostname');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>targetServerIp, 'target_server_ip');
        if (implementors) {
            implementors.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'implementors');
            })
        }
        if (observers) {
            observers.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'observers');
            })
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>startTime, 'start_time');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>endTime, 'end_time');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>ptySessionState, 'pty_session_state');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'page_size');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>totalCount, 'total_count');

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/admin/pty_sessions`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<GetPtySessionResponse>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
