/**
 * Control API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiV1WhitelistRegexIdPutRequest { 
    /**
     * Updated regular expression pattern
     */
    pattern: string;
    isEnabled?: boolean;
}

