/**
 * Control API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of connection being established
 */
export const ConnectionPurpose = {
    ChangeRequest: 'change_request',
    HealthCheck: 'health_check'
} as const;
export type ConnectionPurpose = typeof ConnectionPurpose[keyof typeof ConnectionPurpose];

