/**
 * Control API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConnectionStatus } from './connectionStatus';
import { StartRole } from './startRole';


export interface Connection { 
    id?: string;
    user_id?: string;
    pty_session_id?: string;
    start_role?: StartRole;
    status?: ConnectionStatus;
    join_time?: string;
    leave_time?: string;
}
export namespace Connection {
}


