/**
 * Control API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StartRole } from './startRole';


export interface JoinRequest { 
    /**
     * ID of the existing PTY session to join, user will be validated against this session\'s initial connection details
     */
    pty_session_id: string;
    start_role: StartRole;
}
export namespace JoinRequest {
}


