/**
 * Control API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Connection } from './connection';
import { PtySessionState } from './ptySessionState';
import { ConnectionPurpose } from './connectionPurpose';


export interface PtySession { 
    id?: string;
    created_by?: string;
    start_time?: string;
    end_time?: string;
    state?: PtySessionState;
    last_activity?: string;
    purpose?: ConnectionPurpose;
    /**
     * ID of the change request associated with this PTY session, if applicable
     */
    change_id?: string;
    /**
     * List of connections to this PTY session\'s life time
     */
    connections?: Array<Connection>;
}
export namespace PtySession {
}


