/**
 * Control API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * State of the PTY session
 */
export const PtySessionState = {
    Created: 'created',
    Active: 'active',
    Closed: 'closed'
} as const;
export type PtySessionState = typeof PtySessionState[keyof typeof PtySessionState];

