/**
 * Control API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegexFilter { 
    id?: number;
    pattern?: string;
    ou_group?: string;
    filter_type?: RegexFilter.FilterTypeEnum;
    is_enabled?: boolean;
    created_by?: string;
    created_at?: string;
    deleted_by?: string;
    deleted_at?: string;
    updated_by?: string;
    updated_at?: string;
}
export namespace RegexFilter {
    export const FilterTypeEnum = {
        Whitelist: 'WHITELIST',
        Blacklist: 'BLACKLIST'
    } as const;
    export type FilterTypeEnum = typeof FilterTypeEnum[keyof typeof FilterTypeEnum];
}


