/**
 * Control API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Info about the target server for the PTY session
 */
export interface ServerInfo { 
    /**
     * The Os user to connect as
     */
    os_user: string;
    /**
     * IP address of the target server
     */
    server_ip: string;
}

