/**
 * Control API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServerInfo } from './serverInfo';
import { ConnectionPurpose } from './connectionPurpose';


export interface StartRequest { 
    purpose: ConnectionPurpose;
    /**
     * Only required if purpose is \"change_request\", ID of the change request to connect to
     */
    change_id?: string;
    server: ServerInfo;
}
export namespace StartRequest {
}


