/**
 * Control API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TokenResponse { 
    /**
     * JWT token for proxy
     */
    token: string;
    /**
     * Load balancer URL for proxy group (e.g., `https://proxy.os.com`, `https://proxy.db.com`)
     */
    proxyUrl: string;
}

