/* tslint:disable */
/* eslint-disable */
/**
 * Control API
 * API for starting and joining PTY sessions. Currently also hosting all non-proxy related endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiV1WhitelistRegexIdPutRequest
 */
export interface ApiV1WhitelistRegexIdPutRequest {
    /**
     * Updated regular expression pattern
     * @type {string}
     * @memberof ApiV1WhitelistRegexIdPutRequest
     */
    'pattern': string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1WhitelistRegexIdPutRequest
     */
    'isEnabled'?: boolean;
}

