/* tslint:disable */
/* eslint-disable */
/**
 * Control API
 * API for starting and joining PTY sessions. Currently also hosting all non-proxy related endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HostSessionDetails } from './host-session-details';

/**
 * 
 * @export
 * @interface ChangeRequestSessionsResponse
 */
export interface ChangeRequestSessionsResponse {
    /**
     * 
     * @type {string}
     * @memberof ChangeRequestSessionsResponse
     */
    'change_id'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ChangeRequestSessionsResponse
     */
    'country'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ChangeRequestSessionsResponse
     */
    'lob'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ChangeRequestSessionsResponse
     */
    'implementor_groups'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ChangeRequestSessionsResponse
     */
    'change_start_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeRequestSessionsResponse
     */
    'change_end_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeRequestSessionsResponse
     */
    'change_request_status'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeRequestSessionsResponse
     */
    'summary'?: string;
    /**
     * 
     * @type {Array<HostSessionDetails>}
     * @memberof ChangeRequestSessionsResponse
     */
    'host_session_details'?: Array<HostSessionDetails>;
}

