/* tslint:disable */
/* eslint-disable */
/**
 * Control API
 * API for starting and joining PTY sessions. Currently also hosting all non-proxy related endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ConnectionStatus } from './connection-status';
// May contain unused imports in some cases
// @ts-ignore
import type { StartRole } from './start-role';

/**
 * 
 * @export
 * @interface Connection
 */
export interface Connection {
    /**
     * 
     * @type {string}
     * @memberof Connection
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Connection
     */
    'user_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Connection
     */
    'pty_session_id'?: string;
    /**
     * 
     * @type {StartRole}
     * @memberof Connection
     */
    'start_role'?: StartRole;
    /**
     * 
     * @type {ConnectionStatus}
     * @memberof Connection
     */
    'status'?: ConnectionStatus;
    /**
     * 
     * @type {string}
     * @memberof Connection
     */
    'join_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof Connection
     */
    'leave_time'?: string;
}



