/* tslint:disable */
/* eslint-disable */
/**
 * Control API
 * API for starting and joining PTY sessions. Currently also hosting all non-proxy related endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Type of connection being established
 * @export
 * @enum {string}
 */

export const ConnectionPurpose = {
    ChangeRequest: 'change_request',
    HealthCheck: 'health_check'
} as const;

export type ConnectionPurpose = typeof ConnectionPurpose[keyof typeof ConnectionPurpose];



