/* tslint:disable */
/* eslint-disable */
/**
 * Control API
 * API for starting and joining PTY sessions. Currently also hosting all non-proxy related endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HostSessionDetails } from './host-session-details';

/**
 * 
 * @export
 * @interface HealthcheckSessionsResponse
 */
export interface HealthcheckSessionsResponse {
    /**
     * 
     * @type {Array<HostSessionDetails>}
     * @memberof HealthcheckSessionsResponse
     */
    'host_session_details'?: Array<HostSessionDetails>;
}

