/* tslint:disable */
/* eslint-disable */
/**
 * Control API
 * API for starting and joining PTY sessions. Currently also hosting all non-proxy related endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Host } from './host';
// May contain unused imports in some cases
// @ts-ignore
import type { PtySessionSummary } from './pty-session-summary';

/**
 * 
 * @export
 * @interface HostSessionDetails
 */
export interface HostSessionDetails {
    /**
     * 
     * @type {Host}
     * @memberof HostSessionDetails
     */
    'host'?: Host;
    /**
     * 
     * @type {Array<string>}
     * @memberof HostSessionDetails
     */
    'os_users'?: Array<string>;
    /**
     * 
     * @type {Array<PtySessionSummary>}
     * @memberof HostSessionDetails
     */
    'pty_sessions'?: Array<PtySessionSummary>;
}

