/* tslint:disable */
/* eslint-disable */
/**
 * Control API
 * API for starting and joining PTY sessions. Currently also hosting all non-proxy related endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StartRole } from './start-role';

/**
 * 
 * @export
 * @interface JoinRequest
 */
export interface JoinRequest {
    /**
     * ID of the existing PTY session to join, user will be validated against this session\'s initial connection details
     * @type {string}
     * @memberof JoinRequest
     */
    'pty_session_id': string;
    /**
     * 
     * @type {StartRole}
     * @memberof JoinRequest
     */
    'start_role': StartRole;
}



