/* tslint:disable */
/* eslint-disable */
/**
 * Control API
 * API for starting and joining PTY sessions. Currently also hosting all non-proxy related endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Load balancer information for the proxy group
 * @export
 * @interface ProxyLoadBalancer
 */
export interface ProxyLoadBalancer {
    /**
     * Unique identifier for the load balancer
     * @type {string}
     * @memberof ProxyLoadBalancer
     */
    'id': string;
    /**
     * URL of the load balancer (e.g., `https://proxy.os.com`)
     * @type {string}
     * @memberof ProxyLoadBalancer
     */
    'url': string;
}

