/* tslint:disable */
/* eslint-disable */
/**
 * Control API
 * API for starting and joining PTY sessions. Currently also hosting all non-proxy related endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Connection } from './connection';
// May contain unused imports in some cases
// @ts-ignore
import type { ConnectionPurpose } from './connection-purpose';
// May contain unused imports in some cases
// @ts-ignore
import type { PtySessionState } from './pty-session-state';

/**
 * 
 * @export
 * @interface PtySession
 */
export interface PtySession {
    /**
     * 
     * @type {string}
     * @memberof PtySession
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PtySession
     */
    'created_by'?: string;
    /**
     * 
     * @type {string}
     * @memberof PtySession
     */
    'start_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof PtySession
     */
    'end_time'?: string;
    /**
     * 
     * @type {PtySessionState}
     * @memberof PtySession
     */
    'state'?: PtySessionState;
    /**
     * 
     * @type {string}
     * @memberof PtySession
     */
    'last_activity'?: string;
    /**
     * 
     * @type {ConnectionPurpose}
     * @memberof PtySession
     */
    'purpose'?: ConnectionPurpose;
    /**
     * ID of the change request associated with this PTY session, if applicable
     * @type {string}
     * @memberof PtySession
     */
    'change_id'?: string;
    /**
     * List of connections to this PTY session\'s life time
     * @type {Array<Connection>}
     * @memberof PtySession
     */
    'connections'?: Array<Connection>;
}



