/* tslint:disable */
/* eslint-disable */
/**
 * Control API
 * API for starting and joining PTY sessions. Currently also hosting all non-proxy related endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RegexFilter
 */
export interface RegexFilter {
    /**
     * 
     * @type {number}
     * @memberof RegexFilter
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof RegexFilter
     */
    'pattern'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegexFilter
     */
    'ou_group'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegexFilter
     */
    'filter_type'?: RegexFilterFilterTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof RegexFilter
     */
    'is_enabled'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RegexFilter
     */
    'created_by'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegexFilter
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegexFilter
     */
    'deleted_by'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegexFilter
     */
    'deleted_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegexFilter
     */
    'updated_by'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegexFilter
     */
    'updated_at'?: string;
}

export const RegexFilterFilterTypeEnum = {
    Whitelist: 'WHITELIST',
    Blacklist: 'BLACKLIST'
} as const;

export type RegexFilterFilterTypeEnum = typeof RegexFilterFilterTypeEnum[keyof typeof RegexFilterFilterTypeEnum];


