/* tslint:disable */
/* eslint-disable */
/**
 * Control API
 * API for starting and joining PTY sessions. Currently also hosting all non-proxy related endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Info about the target server for the PTY session
 * @export
 * @interface ServerInfo
 */
export interface ServerInfo {
    /**
     * The Os user to connect as
     * @type {string}
     * @memberof ServerInfo
     */
    'os_user': string;
    /**
     * IP address of the target server
     * @type {string}
     * @memberof ServerInfo
     */
    'server_ip': string;
}

