/* tslint:disable */
/* eslint-disable */
/**
 * Control API
 * API for starting and joining PTY sessions. Currently also hosting all non-proxy related endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Start role for joining existing PTY sessions
 * @export
 * @enum {string}
 */

export const StartRole = {
    Implementor: 'implementor',
    Observer: 'observer'
} as const;

export type StartRole = typeof StartRole[keyof typeof StartRole];



