/* tslint:disable */
/* eslint-disable */
/**
 * Control API
 * API for starting and joining PTY sessions. Currently also hosting all non-proxy related endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ConnectionPurpose } from './connection-purpose';
// May contain unused imports in some cases
// @ts-ignore
import type { ServerInfo } from './server-info';

/**
 * 
 * @export
 * @interface StartRequest
 */
export interface StartRequest {
    /**
     * 
     * @type {ConnectionPurpose}
     * @memberof StartRequest
     */
    'purpose': ConnectionPurpose;
    /**
     * Only required if purpose is \"change_request\", ID of the change request to connect to
     * @type {string}
     * @memberof StartRequest
     */
    'change_id'?: string;
    /**
     * 
     * @type {ServerInfo}
     * @memberof StartRequest
     */
    'server': ServerInfo;
}



