/* tslint:disable */
/* eslint-disable */
/**
 * Control API
 * API for starting and joining PTY sessions. Currently also hosting all non-proxy related endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TokenResponse
 */
export interface TokenResponse {
    /**
     * JWT token for proxy
     * @type {string}
     * @memberof TokenResponse
     */
    'token': string;
    /**
     * Load balancer URL for proxy group (e.g., `https://proxy.os.com`, `https://proxy.db.com`)
     * @type {string}
     * @memberof TokenResponse
     */
    'proxyUrl': string;
}

